name: etl_national_park_passport_data
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  ingest_data_from_google_sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.8"
          architecture: x64
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r workflows_script/requirements.txt
          ls -a
      - name: Run ETL
        working-directory: workflows_script
        run: |
          python etl.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: thailand_nation_park_data
          path: |
            workflows_script/thailand_national_park.json
  commit-to-wiki:
    needs: [ingest_data_from_google_sheet]
    runs-on: ubuntu-latest
    steps:
      - name: Check Repo
        uses: actions/checkout@v2
      - name: Download rubber Artifacts
        uses: actions/download-artifact@v2
        with:
          name: thailand_nation_park_data
          path: |
            wiki/thailand_nation_park_data
      - name: Check file
        run: |
          ls wiki/thailand_nation_park_data/
      - name: Upload JSON to Github Wiki
        uses: kai-tub/external-repo-sync-action@v1
        with:
          source-directory: "wiki/thailand_nation_park_data/"
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
